export {
  Typography,
  Heading,
  Text,
  Code,
  Caption,
  Lead,
  Muted,
  Blockquote,
  type TypographyProps,
  type TypographyVariant,
  type TypographyColor,
  type TypographyAlign,
  type TypographyTransform,
} from "./Typography";
